### ISSUE TITLE
how to add text for every image?

### ISSUE THREAD

**Issue by xingxinggu** [MartinAltmayer/imageflow#1]
I want to add timestamp for every image ,how to do ?

**Comment by MartinAltmayer** [comment]
Hi, thanks for your interest in this library. But please be advised that it is unmaintained and hasn't seen updates for more than 9 years now.

Apparently, rendering of texts is currently broken. As this small library is so old, I'm not really planning to do any updates, sorry!

**Comment by xingxinggu** [comment]
thanks,i have fixed this bymyself
